### ISSUE TITLE
框架代码直接蜜汁报错

### ISSUE THREAD

**Issue by Yitong806** [CharlotteE67/CS305-2022-QA#1]
作业框架中有一个这个代码，每次运行输入后必定报错（此时还没运行到任何NotImplementedError以及需要实现的部分）：

![image](https://user-images.githubusercontent.com/64548919/160274514-96152907-2c2e-423e-b6d5-720283aa9899.png)

报错信息如下所示：

![image](https://user-images.githubusercontent.com/64548919/160274542-cc1bc602-7688-4d78-8c5e-69308786be42.png)

请问该问题应该如何解决？

**Comment by Yitong806** [comment]
补充：网络环境为SUSTech-Wifi校园网环境

**Comment by CharlotteE67** [comment]
Source ip输入的是正确的吗？如果source ip弄错了可能会出现这种情况。在ipconfig里查看ipv4的地址。

**Comment by Yitong806** [comment]
请问source ip是需要填写ipconfig得到的ipv4地址吗？

**Comment by CharlotteE67** [comment]
> 请问source ip是需要填写ipconfig得到的ipv4地址吗？

对的，参考作业文档里的描述

**Comment by Yitong806** [comment]
非常感谢！
