### ISSUE TITLE
可以给一点bonus中视频播放的提示吗

### ISSUE THREAD

**Issue by tian-y-x** [CharlotteE67/CS305-2022-QA#11]

**Comment by tian-y-x** [comment]
如果视频放在服务端，客户端想要播放视频有两种方法：把视频从服务器下载下来；不下载视频而只在线播放。
对于前者，可以用http协议较为简单的实现，但这样做很奇怪，因为各大视频网站下载的视频好像都不带弹幕。对于后者，是否应该采用其他视频流媒体协议(例如rtsp

**Comment by Yhcrown** [comment]
我也有这个问题，如果要使用流媒体协议。对于这个bonus来讲学习成本有点太大了，我只能放弃，写弹幕写着写着就写成视频播放器了。

**Comment by CharlotteE67** [comment]
其实设计的时候希望你们写的是后者，但是你写前者也没关系，都能实现视频播放的效果，只是分数不一定拿满。
（这个bonus就20分，平均分到每个mode就10分，我的建议是准备准备project吧

**Comment by tian-y-x** [comment]
> 其实设计的时候希望你们写的是后者，但是你写前者也没关系，都能实现视频播放的效果，只是分数不一定拿满。 （这个bonus就20分，平均分到每个mode就10分，我的建议是准备准备project吧

project需要准备什么呢？大概是一个什么样的项目

**Comment by CharlotteE67** [comment]
> > 其实设计的时候希望你们写的是后者，但是你写前者也没关系，都能实现视频播放的效果，只是分数不一定拿满。 （这个bonus就20分，平均分到每个mode就10分，我的建议是准备准备project吧
> 
> project需要准备什么呢？大概是一个什么样的项目

额project跟这次作业没关系哈。我只是说project可能会有点难，让大家不用太纠结这次作业的bonus。
