### ISSUE TITLE
关于报告的问题

### ISSUE THREAD

**Issue by Fros1er** [CharlotteE67/CS305-2022-QA#13]
请问报告中需要提供有关功能实现的截图吗？
还是说提供步骤就可以。。
感觉同时开好几个窗口很难截图也很麻烦。。。~~而且我css完全写糊了，缩小窗口的话所有dom元素会乱跑~~

另外，打包的时候需要把视频一起传上去吗

~~假二次元顺便问一句头像的出处~~

**Comment by CharlotteE67** [comment]
截图、步骤、视频都行，如果截图困难就简单描述一下效果，我们到时候也会测试。
css其实老师让我写好不用你们动了...我也没考虑缩小窗口的问题。
最终提交材料包括代码文件以及报告，和其他你觉得需要的文件。
~~头像好像是《天使降临到我身边》的角色，当时不知道，觉得很可爱就用了。~~

**Comment by Fros1er** [comment]
> css其实老师让我写好不用你们动了...
是我写的问题，加了个table进去。。。
总之谢谢(
