### ISSUE TITLE
关于类`DNSHandler`的问题

### ISSUE THREAD

**Issue by Yitong806** [CharlotteE67/CS305-2022-QA#2]
请问能否解释一下`DNSHandler`类中handle方法需要做什么以及有什么功能？这个注释里面的塑料英语让人十分得confusing。

**Comment by Yitong806** [comment]
特别地，想请问一下这个：
```
#TODO: initialize your variable here
```
是想说什么，有可能有哪些variable需要初始化？

**Comment by CharlotteE67** [comment]
DNSHandler里的handle方法是dns服务器收到message之后处理的方法，包括解析message，完成dns query（query方法）以及包装成response的过程。
（如果觉得TODO里不太懂的话建议按"implement your code here"理解，只是告诉你这块要写代码的，这里初始化emmmm大概是某个中间变量吧...（如果不是老师要求我们也不会写成三个类的，直接写成小方法就没了（小声bb

**Comment by Yitong806** [comment]
感谢，最后还想请问一下注释能否出现中文？

**Comment by CharlotteE67** [comment]
这个可以的，你能正常运行你的程序就行。后续我们会人工批改的。

**Comment by Yitong806** [comment]
非常感谢！我可能还有一些其他的问题，希望能够不吝赐教！
