### ISSUE TITLE
Python3.10 get_event_loop: DeprecationWarning

### ISSUE THREAD

**Issue by ChristinaLJC** [CharlotteE67/CS305-2022-QA#4]
![QQ图片20220417140759](https://user-images.githubusercontent.com/44918766/163702911-f30fce86-82d4-4f12-9741-83fa077f8287.png)

用Python3.10来运行这个WS的python文件，会报DeprecationWarning，但是程序不会终止，弹幕系统的功能可以正常运行。

想问一下，有没有什么好的解决办法，让它不报DeprecationWarning。

补充：
![批注 2022-04-17 141152](https://user-images.githubusercontent.com/44918766/163702983-33ff7b42-99c6-41f0-830c-9820ebd928db.png)
官方文档里似乎是说，这种get_event_loop的方式就快被改成get_running_loop了。
我目前的解决是，将这条语句改成如下，不知是否符合要求：（run了以后感觉似乎可行？求明确）
![批注 2022-04-17 141332](https://user-images.githubusercontent.com/44918766/163703050-4ba62bea-c550-4651-a8e6-bf37c157b29f.png)

**Comment by ChristinaLJC** [comment]
http里的这个python文件也是同样的一个问题

**Comment by CharlotteE67** [comment]
使用3.8版本可以解决asyncio的相关问题。当然如果代码上的调整能够解决问题也是可以的，在报告中描述清楚即可，便于我们测试。
