### ISSUE TITLE
WS basic实现的具体要求

### ISSUE THREAD

**Issue by ChristinaLJC** [CharlotteE67/CS305-2022-QA#5]
在WS中，实现到哪种程度算是完成了basic的要求？

1. 如果我同时开两个网页，它们可以互相收到，但是如果我先开一个网页，发了弹幕，然后再开第二个网页，它不会收到在它打开之前第一个网页发的弹幕。
2. 如果我同时开两个网页，它们可以互相收到；如果我先开一个网页，发了弹幕，然后再开第二个网页，它可以收到在它打开之前第一个网页发的弹幕。

要求的程度是1还是2呢？

**Comment by CharlotteE67** [comment]
1

**Comment by ChristinaLJC** [comment]
如果简单地实现了第二种，算bonus吗？

**Comment by CharlotteE67** [comment]
请参考bonus部分video mode，涉及到历史弹幕，即第二种的场景。

**Comment by ChristinaLJC** [comment]
好的谢谢
