### ISSUE TITLE
关于库和时间同步的问题

### ISSUE THREAD

**Issue by Fros1er** [CharlotteE67/CS305-2022-QA#6]
1. 请问能否使用flask？
2. 请问对于视频的播放，假设用户A播放到第60s，用户B播放到第30s，此时A发了弹幕，B应该是30s后显示还是立刻显示？
3. video的话，需要做不同视频的区分吗？

**Comment by CharlotteE67** [comment]
1.可以使用，请在报告中说明环境配置，便于我们测试。
2.对于视频模式，A发送在60s时间节点的弹幕，B应该在60s处看到，即 30s后显示。
3.可以再描述一下吗？我理解的就是普通视频。

**Comment by Fros1er** [comment]
>  3.可以再描述一下吗？我理解的就是普通视频。

我的意思大概是，对于视频A和视频B，它们的弹幕应该分别存储和显示。我们需不需要实现这个功能。。还是只提供一个视频用于演示就可以

**Comment by CharlotteE67** [comment]
从功能上来说是需要的。。。我是不是应该感谢提醒hhh

**Comment by Fros1er** [comment]
> 我是不是应该感谢提醒hhh

~~坏了，我好像问多了~~  
总之谢谢(
