### ISSUE TITLE
运行样例http server报错

### ISSUE THREAD

**Issue by FanZeros** [CharlotteE67/CS305-2022-QA#8]
请问为什么在运行**样例**http server时候会报错？py3.10 ，另一边ws的是可以运行的

![6J2M 3R27Z}1$3T~FPBP8UM](https://user-images.githubusercontent.com/71616828/164147327-a414aeaf-4853-4969-b5cd-a4b0806f8446.png)
![8MOXO`$7)48(FF LERGC$LR](https://user-images.githubusercontent.com/71616828/164147358-f57781fd-a071-45d6-9f23-86c48fd636e8.png)

**Comment by CharlotteE67** [comment]
用python3.8是ok的。3.10可能有些方法变了，如果要用得自己改一下。
